name: CICD Demo class

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: |
          echo "Hello Pranit"
          echo "This is new cicd mm"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Phase
        run: echo "Running TC"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy the app
        run: echo "Deploy app correctly"
